VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"

  config.vm.network :forwarded_port, guest: 80, host: 8080
  #config.vm.network :private_network, ip: "192.168.10.100"
  config.vm.network :private_network, ip: "192.168.111.222"


  config.vm.provision "ansible" do |ansible|
    #ansible.playbook = "provisioning/playbook.yml"
    ansible.playbook = "provisioning/site.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.verbose = 'v'
  end

end
